#!/bin/bash
alias mn="minion"
alias rem="minion remind $@"
alias today="minion find urgent today `date +%Y-%m-%d`"
alias goals="minion open goals"
alias where_in_the_world_is="minion find --archives $@"
