#!/bin/bash
# Keystrokes have value.
alias mn="minion"

# Let's add content.
alias journal="minion template journal $@"
alias remind="minion remind $@"
alias rem="minion remind $@"
alias week="minion template week"
alias weekend="minion template weekend"

# Let's review content.
alias goals="minion open goals"
alias today="minion find urgent today `date +%Y-%m-%d` goal `date +%A`"
alias where_in_the_world_is="minion find --archives $@"

# For development under Zshell
alias testminion="pushd ~/.vim/bundle/minion/tests; ./run_all_tests.sh; popd"
