#!/usr/bin/python
"""fix tags"""
# Copyright 2011 Edward Delaporte <edthedev@gmail.com>
# Licensed under the University of Illinois / NCSA Open Source License 
# http://www.opensource.org/licenses/UoI-NCSA 
# Created: 2011-07-19

import optparse
import os
import sys
import shutil
import subprocess
import datetime

import edthedev_inbox 

parser = optparse.OptionParser()
parser.add_option("-l", "--list", action="store_true", default=False,
                    help="List the    items in the inbox and then exit.")
# parser.add_option("-d", "--directory", help="Folder to walk through.", default="")
# parser.add_option("-f", "--full", help="Handle recent archives as well.", default="")
(options, args) = parser.parse_args()

if len(args) == 0:
	files = edthedev_inbox.getOutput("inbox --list --all").split('\n')
else:
	files = edthedev_inbox.getOutput("inbox --list --all -s %s" % '-s '.join(args)).split('\n')

files_to_tag = []
for f in files:
	if f.count('@') < 2:
		files_to_tag.append(f)

if options.list:
	edthedev_inbox.displayOutput('Files with too few tags', '\n'.join(files_to_tag))
else:
	length = len(files_to_tag)
	for i, f in enumerate(files_to_tag):
		print "%d/%d %s" % (i, length, f)
		edthedev_inbox.addTags(f)
